/* Auto-generated by genmsg_cpp for file /home/dano/projects/ros-fuerte-ws/pteam_p2os/msg/Perception.msg */
#ifndef PTEAM_P2OS_MESSAGE_PERCEPTION_H
#define PTEAM_P2OS_MESSAGE_PERCEPTION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "pteam_p2os/ProcessedLS.h"
#include "nav_msgs/Odometry.h"

namespace pteam_p2os
{
template <class ContainerAllocator>
struct Perception_ {
  typedef Perception_<ContainerAllocator> Type;

  Perception_()
  : laser()
  , odometry()
  {
  }

  Perception_(const ContainerAllocator& _alloc)
  : laser(_alloc)
  , odometry(_alloc)
  {
  }

  typedef  ::pteam_p2os::ProcessedLS_<ContainerAllocator>  _laser_type;
   ::pteam_p2os::ProcessedLS_<ContainerAllocator>  laser;

  typedef  ::nav_msgs::Odometry_<ContainerAllocator>  _odometry_type;
   ::nav_msgs::Odometry_<ContainerAllocator>  odometry;


  typedef boost::shared_ptr< ::pteam_p2os::Perception_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pteam_p2os::Perception_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Perception
typedef  ::pteam_p2os::Perception_<std::allocator<void> > Perception;

typedef boost::shared_ptr< ::pteam_p2os::Perception> PerceptionPtr;
typedef boost::shared_ptr< ::pteam_p2os::Perception const> PerceptionConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::pteam_p2os::Perception_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::pteam_p2os::Perception_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace pteam_p2os

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::pteam_p2os::Perception_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::pteam_p2os::Perception_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::pteam_p2os::Perception_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dd39913e347f9f33272c03167679aa77";
  }

  static const char* value(const  ::pteam_p2os::Perception_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xdd39913e347f9f33ULL;
  static const uint64_t static_value2 = 0x272c03167679aa77ULL;
};

template<class ContainerAllocator>
struct DataType< ::pteam_p2os::Perception_<ContainerAllocator> > {
  static const char* value() 
  {
    return "pteam_p2os/Perception";
  }

  static const char* value(const  ::pteam_p2os::Perception_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::pteam_p2os::Perception_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ProcessedLS laser\n\
nav_msgs/Odometry odometry\n\
\n\
================================================================================\n\
MSG: pteam_p2os/ProcessedLS\n\
Header header\n\
sensor_msgs/LaserScan data\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/LaserScan\n\
# Single scan from a planar laser range-finder\n\
#\n\
# If you have another ranging device with different behavior (e.g. a sonar\n\
# array), please find or create a different message, since applications\n\
# will make fairly laser-specific assumptions about this data\n\
\n\
Header header            # timestamp in the header is the acquisition time of \n\
                         # the first ray in the scan.\n\
                         #\n\
                         # in frame frame_id, angles are measured around \n\
                         # the positive Z axis (counterclockwise, if Z is up)\n\
                         # with zero angle being forward along the x axis\n\
                         \n\
float32 angle_min        # start angle of the scan [rad]\n\
float32 angle_max        # end angle of the scan [rad]\n\
float32 angle_increment  # angular distance between measurements [rad]\n\
\n\
float32 time_increment   # time between measurements [seconds] - if your scanner\n\
                         # is moving, this will be used in interpolating position\n\
                         # of 3d points\n\
float32 scan_time        # time between scans [seconds]\n\
\n\
float32 range_min        # minimum range value [m]\n\
float32 range_max        # maximum range value [m]\n\
\n\
float32[] ranges         # range data [m] (Note: values < range_min or > range_max should be discarded)\n\
float32[] intensities    # intensity data [device-specific units].  If your\n\
                         # device does not provide intensities, please leave\n\
                         # the array empty.\n\
\n\
================================================================================\n\
MSG: nav_msgs/Odometry\n\
# This represents an estimate of a position and velocity in free space.  \n\
# The pose in this message should be specified in the coordinate frame given by header.frame_id.\n\
# The twist in this message should be specified in the coordinate frame given by the child_frame_id\n\
Header header\n\
string child_frame_id\n\
geometry_msgs/PoseWithCovariance pose\n\
geometry_msgs/TwistWithCovariance twist\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseWithCovariance\n\
# This represents a pose in free space with uncertainty.\n\
\n\
Pose pose\n\
\n\
# Row-major representation of the 6x6 covariance matrix\n\
# The orientation parameters use a fixed-axis representation.\n\
# In order, the parameters are:\n\
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n\
float64[36] covariance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/TwistWithCovariance\n\
# This expresses velocity in free space with uncertianty.\n\
\n\
Twist twist\n\
\n\
# Row-major representation of the 6x6 covariance matrix\n\
# The orientation parameters use a fixed-axis representation.\n\
# In order, the parameters are:\n\
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n\
float64[36] covariance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into it's linear and angular parts. \n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::pteam_p2os::Perception_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::pteam_p2os::Perception_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.laser);
    stream.next(m.odometry);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Perception_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pteam_p2os::Perception_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::pteam_p2os::Perception_<ContainerAllocator> & v) 
  {
    s << indent << "laser: ";
s << std::endl;
    Printer< ::pteam_p2os::ProcessedLS_<ContainerAllocator> >::stream(s, indent + "  ", v.laser);
    s << indent << "odometry: ";
s << std::endl;
    Printer< ::nav_msgs::Odometry_<ContainerAllocator> >::stream(s, indent + "  ", v.odometry);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PTEAM_P2OS_MESSAGE_PERCEPTION_H

