"""autogenerated by genpy from pteam_p2os/Perception.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import sensor_msgs.msg
import std_msgs.msg
import nav_msgs.msg
import pteam_p2os.msg

class Perception(genpy.Message):
  _md5sum = "dd39913e347f9f33272c03167679aa77"
  _type = "pteam_p2os/Perception"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """ProcessedLS laser
nav_msgs/Odometry odometry

================================================================================
MSG: pteam_p2os/ProcessedLS
Header header
sensor_msgs/LaserScan data

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: sensor_msgs/LaserScan
# Single scan from a planar laser range-finder
#
# If you have another ranging device with different behavior (e.g. a sonar
# array), please find or create a different message, since applications
# will make fairly laser-specific assumptions about this data

Header header            # timestamp in the header is the acquisition time of 
                         # the first ray in the scan.
                         #
                         # in frame frame_id, angles are measured around 
                         # the positive Z axis (counterclockwise, if Z is up)
                         # with zero angle being forward along the x axis
                         
float32 angle_min        # start angle of the scan [rad]
float32 angle_max        # end angle of the scan [rad]
float32 angle_increment  # angular distance between measurements [rad]

float32 time_increment   # time between measurements [seconds] - if your scanner
                         # is moving, this will be used in interpolating position
                         # of 3d points
float32 scan_time        # time between scans [seconds]

float32 range_min        # minimum range value [m]
float32 range_max        # maximum range value [m]

float32[] ranges         # range data [m] (Note: values < range_min or > range_max should be discarded)
float32[] intensities    # intensity data [device-specific units].  If your
                         # device does not provide intensities, please leave
                         # the array empty.

================================================================================
MSG: nav_msgs/Odometry
# This represents an estimate of a position and velocity in free space.  
# The pose in this message should be specified in the coordinate frame given by header.frame_id.
# The twist in this message should be specified in the coordinate frame given by the child_frame_id
Header header
string child_frame_id
geometry_msgs/PoseWithCovariance pose
geometry_msgs/TwistWithCovariance twist

================================================================================
MSG: geometry_msgs/PoseWithCovariance
# This represents a pose in free space with uncertainty.

Pose pose

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of postion and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/TwistWithCovariance
# This expresses velocity in free space with uncertianty.

Twist twist

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into it's linear and angular parts. 
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 

float64 x
float64 y
float64 z
"""
  __slots__ = ['laser','odometry']
  _slot_types = ['pteam_p2os/ProcessedLS','nav_msgs/Odometry']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       laser,odometry

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Perception, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.laser is None:
        self.laser = pteam_p2os.msg.ProcessedLS()
      if self.odometry is None:
        self.odometry = nav_msgs.msg.Odometry()
    else:
      self.laser = pteam_p2os.msg.ProcessedLS()
      self.odometry = nav_msgs.msg.Odometry()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.laser.header.seq, _x.laser.header.stamp.secs, _x.laser.header.stamp.nsecs))
      _x = self.laser.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.laser.data.header.seq, _x.laser.data.header.stamp.secs, _x.laser.data.header.stamp.nsecs))
      _x = self.laser.data.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7f.pack(_x.laser.data.angle_min, _x.laser.data.angle_max, _x.laser.data.angle_increment, _x.laser.data.time_increment, _x.laser.data.scan_time, _x.laser.data.range_min, _x.laser.data.range_max))
      length = len(self.laser.data.ranges)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.laser.data.ranges))
      length = len(self.laser.data.intensities)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.laser.data.intensities))
      _x = self
      buff.write(_struct_3I.pack(_x.odometry.header.seq, _x.odometry.header.stamp.secs, _x.odometry.header.stamp.nsecs))
      _x = self.odometry.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.odometry.child_frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d.pack(_x.odometry.pose.pose.position.x, _x.odometry.pose.pose.position.y, _x.odometry.pose.pose.position.z, _x.odometry.pose.pose.orientation.x, _x.odometry.pose.pose.orientation.y, _x.odometry.pose.pose.orientation.z, _x.odometry.pose.pose.orientation.w))
      buff.write(_struct_36d.pack(*self.odometry.pose.covariance))
      _x = self
      buff.write(_struct_6d.pack(_x.odometry.twist.twist.linear.x, _x.odometry.twist.twist.linear.y, _x.odometry.twist.twist.linear.z, _x.odometry.twist.twist.angular.x, _x.odometry.twist.twist.angular.y, _x.odometry.twist.twist.angular.z))
      buff.write(_struct_36d.pack(*self.odometry.twist.covariance))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.laser is None:
        self.laser = pteam_p2os.msg.ProcessedLS()
      if self.odometry is None:
        self.odometry = nav_msgs.msg.Odometry()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.laser.header.seq, _x.laser.header.stamp.secs, _x.laser.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.laser.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.laser.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.laser.data.header.seq, _x.laser.data.header.stamp.secs, _x.laser.data.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.laser.data.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.laser.data.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.laser.data.angle_min, _x.laser.data.angle_max, _x.laser.data.angle_increment, _x.laser.data.time_increment, _x.laser.data.scan_time, _x.laser.data.range_min, _x.laser.data.range_max,) = _struct_7f.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.laser.data.ranges = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.laser.data.intensities = struct.unpack(pattern, str[start:end])
      _x = self
      start = end
      end += 12
      (_x.odometry.header.seq, _x.odometry.header.stamp.secs, _x.odometry.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.odometry.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.odometry.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.odometry.child_frame_id = str[start:end].decode('utf-8')
      else:
        self.odometry.child_frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.odometry.pose.pose.position.x, _x.odometry.pose.pose.position.y, _x.odometry.pose.pose.position.z, _x.odometry.pose.pose.orientation.x, _x.odometry.pose.pose.orientation.y, _x.odometry.pose.pose.orientation.z, _x.odometry.pose.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      start = end
      end += 288
      self.odometry.pose.covariance = _struct_36d.unpack(str[start:end])
      _x = self
      start = end
      end += 48
      (_x.odometry.twist.twist.linear.x, _x.odometry.twist.twist.linear.y, _x.odometry.twist.twist.linear.z, _x.odometry.twist.twist.angular.x, _x.odometry.twist.twist.angular.y, _x.odometry.twist.twist.angular.z,) = _struct_6d.unpack(str[start:end])
      start = end
      end += 288
      self.odometry.twist.covariance = _struct_36d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.laser.header.seq, _x.laser.header.stamp.secs, _x.laser.header.stamp.nsecs))
      _x = self.laser.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.laser.data.header.seq, _x.laser.data.header.stamp.secs, _x.laser.data.header.stamp.nsecs))
      _x = self.laser.data.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7f.pack(_x.laser.data.angle_min, _x.laser.data.angle_max, _x.laser.data.angle_increment, _x.laser.data.time_increment, _x.laser.data.scan_time, _x.laser.data.range_min, _x.laser.data.range_max))
      length = len(self.laser.data.ranges)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.laser.data.ranges.tostring())
      length = len(self.laser.data.intensities)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.laser.data.intensities.tostring())
      _x = self
      buff.write(_struct_3I.pack(_x.odometry.header.seq, _x.odometry.header.stamp.secs, _x.odometry.header.stamp.nsecs))
      _x = self.odometry.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.odometry.child_frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d.pack(_x.odometry.pose.pose.position.x, _x.odometry.pose.pose.position.y, _x.odometry.pose.pose.position.z, _x.odometry.pose.pose.orientation.x, _x.odometry.pose.pose.orientation.y, _x.odometry.pose.pose.orientation.z, _x.odometry.pose.pose.orientation.w))
      buff.write(self.odometry.pose.covariance.tostring())
      _x = self
      buff.write(_struct_6d.pack(_x.odometry.twist.twist.linear.x, _x.odometry.twist.twist.linear.y, _x.odometry.twist.twist.linear.z, _x.odometry.twist.twist.angular.x, _x.odometry.twist.twist.angular.y, _x.odometry.twist.twist.angular.z))
      buff.write(self.odometry.twist.covariance.tostring())
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.laser is None:
        self.laser = pteam_p2os.msg.ProcessedLS()
      if self.odometry is None:
        self.odometry = nav_msgs.msg.Odometry()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.laser.header.seq, _x.laser.header.stamp.secs, _x.laser.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.laser.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.laser.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.laser.data.header.seq, _x.laser.data.header.stamp.secs, _x.laser.data.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.laser.data.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.laser.data.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.laser.data.angle_min, _x.laser.data.angle_max, _x.laser.data.angle_increment, _x.laser.data.time_increment, _x.laser.data.scan_time, _x.laser.data.range_min, _x.laser.data.range_max,) = _struct_7f.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.laser.data.ranges = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.laser.data.intensities = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 12
      (_x.odometry.header.seq, _x.odometry.header.stamp.secs, _x.odometry.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.odometry.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.odometry.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.odometry.child_frame_id = str[start:end].decode('utf-8')
      else:
        self.odometry.child_frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.odometry.pose.pose.position.x, _x.odometry.pose.pose.position.y, _x.odometry.pose.pose.position.z, _x.odometry.pose.pose.orientation.x, _x.odometry.pose.pose.orientation.y, _x.odometry.pose.pose.orientation.z, _x.odometry.pose.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      start = end
      end += 288
      self.odometry.pose.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      _x = self
      start = end
      end += 48
      (_x.odometry.twist.twist.linear.x, _x.odometry.twist.twist.linear.y, _x.odometry.twist.twist.linear.z, _x.odometry.twist.twist.angular.x, _x.odometry.twist.twist.angular.y, _x.odometry.twist.twist.angular.z,) = _struct_6d.unpack(str[start:end])
      start = end
      end += 288
      self.odometry.twist.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_7f = struct.Struct("<7f")
_struct_3I = struct.Struct("<3I")
_struct_7d = struct.Struct("<7d")
_struct_6d = struct.Struct("<6d")
_struct_36d = struct.Struct("<36d")
